spring.application.name=ProLink
# Désactive la persistance des sessions sur le disque
server.servlet.session.persistent=false
#Pour voir les modification sans redemarrer
spring.thymeleaf.cache=false
#active le redemarage automatique
spring.devtools.restart.enabled=true
# ==========================================
# 1. CONFIGURATION DE LA BASE DE DONNÉES (XAMPP)
# ==========================================
# Note l'utilisation du pilote MySQL standard fourni avec XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/prolink_v2?useSSL=false&serverTimezone=Africa/Douala&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Par défaut dans XAMPP, le mot de passe est VIDE (ne mets rien après le =. Pas d'espace, rien !)
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 2. CONFIGURATION DE HIBERNATE / JPA
# ==========================================
# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# ==========================================
# 3. CONFIGURATION DE L'API GOOGLE SIGN-IN (OAuth2) - CONFIGURÉ
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
application-secrets.properties
.env